/** Generated by scripts/sync-icline-docs.mjs — do not edit by hand. */
export const ICLINE_BUILD_METADATA = {
	releaseVersion: "0.1.18",
	devBuildNumber: 4,
	devBuildLabel: "dev build 4",
	builtAt: "2026-07-18 07:53",
	upstreamClineSyncedVersion: "v3.89.2",
	upstreamClineSyncedAt: "2026-06-21",
	upstreamClineRepo: "https://github.com/cline/cline",
} as const
