/** Generated by scripts/sync-icline-docs.mjs — do not edit by hand. */
export const ICLINE_BUILD_METADATA = {
	releaseVersion: "0.1.18",
	devBuildNumber: 5,
	devBuildLabel: "dev build 5",
	builtAt: "2026-08-05 15:13",
	upstreamClineSyncedVersion: "v4.0.0 SDK (main@402b9994d)",
	upstreamClineSyncedAt: "2026-07-21",
	upstreamClineRepo: "https://github.com/cline/cline",
} as const
